"""Kinematic structure factors for powder reflections.

F(hkl) = Σ_j occ_j · f_j(k) · Σ_m T_jm(h) · exp(2πi h·(R_m x_j + t_m))

where the inner sum runs over a per-atom subset of symmetry operations chosen
once per refinement stage so that special-position images are not double
counted (the *operation subset* is frozen — a discrete object — while the
positions it produces remain smooth functions of the refined coordinates),
f_j is the Waasmaier-Kirfel form factor with k = sin(θ)/λ, and T is the
Debye-Waller factor (International Tables C).  Intensities use |F|² with the
reflection multiplicity applied separately (Rietveld, 1969, J. Appl. Cryst.
2, 65).

**Anomalous scattering and the powder average.**  With dispersion the species
factor is complex, f = f₀(k) + f′(λ) + i·f″(λ), and Friedel's law dies in a
non-centrosymmetric group: |F(h)|² ≠ |F(−h)|².  A powder cannot resolve the
pair — d(h) = d(−h), they land in one peak — and ``symmetry.generate_reflections``
accordingly merges ±h into a single orbit and keeps one representative.  So
what this module must return is the **orbit average**, not the representative's
own value.  Splitting the species factor into its real and imaginary parts,

    A(h) = Σ_j occ_j·(f₀_j + f′_j)·Σ_m T_jm·exp(2πi h·x_jm)
    B(h) = Σ_j occ_j·      f″_j  ·Σ_m T_jm·exp(2πi h·x_jm)

gives F = A + iB, and since T is real, F(−h) = conj(A − iB), so

    ⟨|F|²⟩ = ½(|F(h)|² + |F(−h)|²) = |A|² + |B|²

*exactly*, over the same orbit sums — no second pass over the orbit, and no
centro/non-centro case split (in a centrosymmetric group A and B share one
common phase, so the cross term vanishes identically).  f″ = 0 makes B ≡ 0 and
recovers |F|², so a structure without a dispersion block is bit-identical to
the non-anomalous model.  Conventions and the tabulation: ``crystallography.
dispersion``.

**Isotropic** sites take T = exp(−B_j k²), identical for every image, so it
factors out of the orbit sum.  **Anisotropic** sites (an ``AnisoU`` block on
the atom) take

    T_jm(h) = exp(−2π² qᵀ·U*_j·q),    q = R_mᵀ·h,   U*_ij = U^ij·a*_i·a*_j

which does *not* factor out — the image generated by R has the transformed
tensor R·U*·Rᵀ, and evaluating that at h is identically evaluating the parent
tensor at the transposed-rotation index R_mᵀh (the reciprocal-space action,
see ``symmetry.py``).  Working in U* rather than U^ij makes that identity
exact rather than contingent on a*·R = R·a*.  Conventions and conversions:
``crystallography.adp``.
"""

from __future__ import annotations

from dataclasses import dataclass, field

import gemmi
import numpy as np

from ..backend import get_backend
from ..schemas.structure import Phase
from .adp import VOIGT, ustar_from_ucif
from .scattering import f0, normalize_species
from .symmetry import get_spacegroup


@dataclass
class PhaseSites:
    """Frozen symmetry-operation subsets for one phase.

    For asymmetric-unit atom ``j``, ``ops[j]`` is a pair of arrays
    ``(R (m_j,3,3), t (m_j,3))`` — the operations that generate *distinct*
    orbit images at the atom's compile-time coordinates.  ``m_j`` is the site
    multiplicity.  ``aniso[j]`` says which Debye-Waller form atom ``j`` uses;
    like the op subsets it is decided at compile time and frozen for the
    stage (it comes from the schema, never from θ).

    ``f_anom[j]`` is the atom's dispersion correction f′ + i·f″, ``None`` when
    the source declares none.  It is frozen for the same reason the op subsets
    are, but more strongly: it depends only on the species and the wavelength,
    and ``EmissionLine.wavelength`` is a plain float rather than a
    ``Parameter``, so it can never be a function of θ.
    """

    ops: list[tuple[np.ndarray, np.ndarray]]
    species: list[str]
    aniso: list[bool] = field(default_factory=list)
    f_anom: np.ndarray | None = None  # (n_asym,) complex128

    def __post_init__(self) -> None:
        if not self.aniso:
            self.aniso = [False] * len(self.species)
        if self.f_anom is not None:
            self.f_anom = np.asarray(self.f_anom, dtype=np.complex128)
            if self.f_anom.shape != (len(self.species),):
                raise ValueError(
                    f"f_anom must have one entry per asymmetric-unit atom "
                    f"({len(self.species)}), got shape {self.f_anom.shape}")

    @property
    def n_asym(self) -> int:
        return len(self.species)

    @property
    def any_aniso(self) -> bool:
        return any(self.aniso)


def select_orbit_ops(sg: gemmi.SpaceGroup, xyz: np.ndarray, *, tol: float = 1e-4
                     ) -> tuple[np.ndarray, np.ndarray]:
    """Choose the operation subset giving distinct images of ``xyz``.

    On a general position this is all operations; on a special position,
    coincident images are dropped so each orbit member appears exactly once.
    """
    rots, trans, seen = [], [], []
    for op in sg.operations():
        r = np.array(op.rot, dtype=np.float64) / gemmi.Op.DEN
        t = np.array(op.tran, dtype=np.float64) / gemmi.Op.DEN
        p = (r @ np.asarray(xyz, dtype=np.float64) + t) % 1.0
        dup = False
        for q in seen:
            diff = np.abs(p - q)
            diff = np.minimum(diff, 1.0 - diff)
            if np.all(diff < tol):
                dup = True
                break
        if not dup:
            seen.append(p)
            rots.append(r)
            trans.append(t)
    return np.asarray(rots), np.asarray(trans)


def compile_phase_sites(phase: Phase,
                        f_anom: dict[str, complex] | None = None) -> PhaseSites:
    """Freeze the per-atom symmetry and species data for one stage.

    ``f_anom`` maps a **raw** ``Atom.species`` string (``"Zn2+"``, not the
    normalised form-factor key) to its dispersion correction f′ + i·f″;
    ``None`` leaves the phase non-anomalous.  The caller resolves it, because
    it is a property of the *source* wavelength rather than of the structure —
    see ``model.forward.compile_model``.
    """
    sg = get_spacegroup(phase.space_group)
    ops: list[tuple[np.ndarray, np.ndarray]] = []
    species: list[str] = []
    aniso: list[bool] = []
    for atom in phase.atoms:
        xyz = np.array([atom.x.value, atom.y.value, atom.z.value])
        ops.append(select_orbit_ops(sg, xyz))
        species.append(normalize_species(atom.species))
        aniso.append(atom.aniso is not None)
    fa = None
    if f_anom is not None:
        fa = np.array([complex(f_anom[a.species]) for a in phase.atoms],
                      dtype=np.complex128)
    return PhaseSites(ops=ops, species=species, aniso=aniso, f_anom=fa)


def transposed_rotation_indices(hkl: np.ndarray, rot: np.ndarray) -> np.ndarray:
    """q_mn = R_mᵀ·h_n for every op and reflection, shape (m, N, 3).

    The reciprocal-space action is the **transposed** rotation (see the
    comment in ``symmetry.py``); getting this wrong is invisible in cubic
    settings and wrong everywhere else.
    """
    xp = get_backend()
    return xp.einsum("nk,mkc->mnc", xp.asarray(hkl, dtype=np.float64), rot)


def _aniso_dw(hkl: np.ndarray, rot: np.ndarray, u6, astar: np.ndarray) -> np.ndarray:
    """exp(−2π² qᵀU*q) per (op, reflection), shape (m, N)."""
    xp = get_backend()
    q = transposed_rotation_indices(hkl, rot)
    ustar = ustar_from_ucif(u6, astar)
    return xp.exp(-2.0 * xp.pi ** 2 * xp.einsum("mnc,cd,mnd->mn", q, ustar, q))


def _orbit_terms(hkl, k, sites, xyz, occ, biso, uaniso, astar, j):
    """Per-atom pieces of F: ``(amp_a, amp_b, phase (m,N), dw (m,N) | None)``.

    ``amp_a`` is the real prefactor occ·(f₀ + f′) that multiplies the orbit sum
    in A and ``amp_b`` the occ·f″ one that multiplies it in B (both (N,); see
    the module docstring).  ``amp_b`` is ``None`` — not a zero array — when the
    phase carries no dispersion, so the off path does no arithmetic at all;
    that test is compile-time structural (``sites.f_anom``), never a branch on
    θ, so it does not break residual purity.  ``dw`` is the per-image
    Debye-Waller factor, ``None`` for isotropic sites (whose factor is already
    folded into the amplitudes).  Sharing this between the forward model and
    the two derivative routines is what keeps their expansions of F literally
    the same expression.

    The amplitude is deliberately built as ``occ·f·dw`` in that association
    order: fp multiplication is not associative, and regrouping it (say to
    share an ``occ·dw`` prefactor between A and B) moves the non-anomalous
    path off its backend goldens by an ulp.
    """
    xp = get_backend()
    rot, tran = sites.ops[j]
    positions = rot @ xyz[j] + tran  # (m, 3)
    phase = xp.exp(2.0j * xp.pi * (positions @ hkl.T))  # (m, N)
    fa = None if sites.f_anom is None else sites.f_anom[j]
    f = f0(sites.species[j], k)
    if fa is not None:
        f = f + float(fa.real)
    if sites.aniso[j]:
        dw = _aniso_dw(hkl, rot, uaniso[j], astar)
        amp_b = None if fa is None else occ[j] * float(fa.imag)
        return occ[j] * f, amp_b, phase, dw
    dw = xp.exp(-biso[j] * k * k)  # exp(−B (sinθ/λ)²)
    amp_b = None if fa is None else occ[j] * float(fa.imag) * dw
    return occ[j] * f * dw, amp_b, phase, None


def _orbit_sum(phase: np.ndarray, dw: np.ndarray | None) -> np.ndarray:
    """Σ_m T_m·exp(2πi h·x_m) — the isotropic T factored out already."""
    return phase.sum(axis=0) if dw is None else (phase * dw).sum(axis=0)


def _structure_factors_ab(h, k, sites, xyz, occ, biso, uaniso, astar):
    """(A, B) of the module docstring; ``B`` is ``None`` without dispersion."""
    xp = get_backend()
    A = xp.zeros(len(h), dtype=np.complex128)
    B = None if sites.f_anom is None else xp.zeros(len(h), dtype=np.complex128)
    for j in range(sites.n_asym):
        amp_a, amp_b, phase, dw = _orbit_terms(
            h, k, sites, xyz, occ, biso, uaniso, astar, j)
        orbit = _orbit_sum(phase, dw)
        A = A + amp_a * orbit
        if B is not None:
            B = B + amp_b * orbit
    return A, B


def _abs2(z) -> np.ndarray:
    xp = get_backend()
    return xp.real(z * xp.conj(z))


def structure_factors_squared(
    hkl: np.ndarray,
    d: np.ndarray,
    sites: PhaseSites,
    xyz: np.ndarray,
    occ: np.ndarray,
    biso: np.ndarray,
    uaniso: np.ndarray | None = None,
    astar: np.ndarray | None = None,
) -> np.ndarray:
    """Powder |F(hkl)|² for each reflection — Friedel-averaged (see module docs).

    Without dispersion this is |F|² exactly as before; with it, the value
    returned is ⟨|F|²⟩ = |A|² + |B|², the average over the ±h orbit the powder
    peak actually contains.

    Parameters
    ----------
    hkl, d : (N,3) reflection indices and current d-spacings (Å).
    sites : frozen per-atom symmetry-operation subsets (and f′ + i·f″).
    xyz : (n_asym, 3) current fractional coordinates.
    occ, biso : (n_asym,) occupancies and isotropic B (Å²).
    uaniso : (n_asym, 6) CIF U^ij (Å²) in (11, 22, 33, 12, 13, 23) order.
        Only rows where ``sites.aniso[j]`` is set are read; required when any
        are.  ``astar`` is then the (3,) reciprocal axis lengths of the
        current cell (they move with the cell, hence a per-call argument
        rather than something frozen into ``sites``).
    """
    xp = get_backend()
    k = 1.0 / (2.0 * xp.asarray(d, dtype=np.float64))  # sinθ/λ = 1/(2d)
    h = xp.asarray(hkl, dtype=np.float64)
    A, B = _structure_factors_ab(h, k, sites, xyz, occ, biso, uaniso, astar)
    return _abs2(A) if B is None else _abs2(A) + _abs2(B)


def d_f2_d_xyz(
    hkl: np.ndarray,
    d: np.ndarray,
    sites: PhaseSites,
    xyz: np.ndarray,
    occ: np.ndarray,
    biso: np.ndarray,
    j: int,
    uaniso: np.ndarray | None = None,
    astar: np.ndarray | None = None,
) -> np.ndarray:
    """Analytic ∂⟨|F|²⟩/∂x_j over the frozen op subsets, shape (N, 3).

    With A = Σ_j' a_j'·G_j', a_j the real occ·(f₀+f′)(·Debye-Waller, isotropic
    sites only) prefactor and G_j = Σ_m T_jm·exp(2πi h·(R_m x_j + t_m)),

        ∂A/∂x_jc = a_j · 2πi Σ_m (R_mᵀ h)_c · T_jm · exp(2πi h·(R_m x_j + t_m))

    — the reciprocal-space action is the **transposed** rotation (see
    ``symmetry.py``) — and ∂|A|²/∂x_jc = 2·Re(Ā · ∂A/∂x_jc) (structure-
    factor derivatives per Rietveld, 1969, J. Appl. Cryst. 2, 65).  T_jm is
    the per-image Debye-Waller factor, which is constant over the orbit for
    an isotropic site and image-dependent for an anisotropic one; either way
    it is independent of x_j, so it rides along unchanged.  The op subsets
    are the same frozen ``sites.ops`` the forward model uses, so the gradient
    is exact for the model as compiled.

    B differs from A only in its per-atom prefactor, so it shares the whole
    bracketed sum: the anomalous term costs one extra multiply-and-accumulate,
    not a second expansion.
    """
    xp = get_backend()
    k = 1.0 / (2.0 * xp.asarray(d, dtype=np.float64))
    h = xp.asarray(hkl, dtype=np.float64)
    A = xp.zeros(len(h), dtype=np.complex128)
    B = None if sites.f_anom is None else xp.zeros(len(h), dtype=np.complex128)
    dA = xp.zeros((len(h), 3), dtype=np.complex128)
    dB = None if B is None else xp.zeros((len(h), 3), dtype=np.complex128)
    for jj in range(sites.n_asym):
        amp_a, amp_b, phase, dw = _orbit_terms(
            h, k, sites, xyz, occ, biso, uaniso, astar, jj)
        orbit = _orbit_sum(phase, dw)
        A = A + amp_a * orbit
        if B is not None:
            B = B + amp_b * orbit
        if jj == j:
            rth = transposed_rotation_indices(h, sites.ops[jj][0])  # (m, N, 3)
            weighted = phase if dw is None else phase * dw
            bracket = (weighted[:, :, None] * rth).sum(axis=0)
            dA = amp_a[:, None] * (2.0j * xp.pi) * bracket
            if dB is not None:
                dB = amp_b[:, None] * (2.0j * xp.pi) * bracket
    out = 2.0 * xp.real(xp.conj(A)[:, None] * dA)
    if B is not None:
        out = out + 2.0 * xp.real(xp.conj(B)[:, None] * dB)
    return out


def d_f2_d_uaniso(
    hkl: np.ndarray,
    d: np.ndarray,
    sites: PhaseSites,
    xyz: np.ndarray,
    occ: np.ndarray,
    biso: np.ndarray,
    j: int,
    uaniso: np.ndarray,
    astar: np.ndarray,
) -> np.ndarray:
    """Analytic ∂⟨|F|²⟩/∂U^ij for anisotropic atom ``j``, shape (N, 6).

    The exponent of the image-m Debye-Waller factor is

        E_m = −2π² Σ_cd q_c q_d a*_c a*_d U^cd,      q = R_mᵀ h,

    so with the six components stored as (11, 22, 33, 12, 13, 23) the packed
    partials pick up the usual factor of two off the diagonal (U^cd and U^dc
    are the same stored number):

        ∂E_m/∂U^cd = −2π² a*_c a*_d q_c q_d · (1 if c = d else 2)

    and ∂A/∂U^cd = a_j·Σ_m T_jm·exp(2πi h·x_jm)·∂E_m/∂U^cd, closed by
    ∂|A|²/∂U = 2·Re(Ā·∂A/∂U) and the matching B term (see
    :func:`d_f2_d_xyz` — the per-component sum is shared, only the prefactor
    differs).  Columns are in the same order as
    ``crystallography.adp.U_NAMES``, which is what the Wyckoff ADP constraint
    rows are written in.

    Like :func:`d_f2_d_xyz` this is Jacobian *support* — host-side analytic
    columns, never traced by an autodiff backend (which differentiates the
    residual itself) — so the in-place per-component buffer writes are fine.
    """
    xp = get_backend()
    k = 1.0 / (2.0 * xp.asarray(d, dtype=np.float64))
    h = xp.asarray(hkl, dtype=np.float64)
    s = xp.asarray(astar, dtype=np.float64)
    A = xp.zeros(len(h), dtype=np.complex128)
    B = None if sites.f_anom is None else xp.zeros(len(h), dtype=np.complex128)
    dA = np.zeros((len(h), 6), dtype=np.complex128)
    dB = None if B is None else np.zeros((len(h), 6), dtype=np.complex128)
    for jj in range(sites.n_asym):
        amp_a, amp_b, phase, dw = _orbit_terms(
            h, k, sites, xyz, occ, biso, uaniso, astar, jj)
        orbit = _orbit_sum(phase, dw)
        A = A + amp_a * orbit
        if B is not None:
            B = B + amp_b * orbit
        if jj == j:
            if dw is None:
                raise ValueError(f"atom {j} is isotropic: no U^ij to differentiate")
            q = transposed_rotation_indices(h, sites.ops[jj][0])  # (m, N, 3)
            for v, (c, e) in enumerate(VOIGT):
                fold = 1.0 if c == e else 2.0
                de = (-2.0 * xp.pi ** 2 * fold * s[c] * s[e]) * q[:, :, c] * q[:, :, e]
                bracket = (phase * dw * de).sum(axis=0)
                dA[:, v] = amp_a * bracket
                if dB is not None:
                    dB[:, v] = amp_b * bracket
    out = 2.0 * xp.real(xp.conj(A)[:, None] * dA)
    if B is not None:
        out = out + 2.0 * xp.real(xp.conj(B)[:, None] * dB)
    return out
